export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const FETCH_TEACHER_SUBJECTS_START = "FETCH_TEACHER_SUBJECTS_START";
export const FETCH_TEACHER_SUBJECTS_SUCCESS = "FETCH_TEACHER_SUBJECTS_SUCCESS";
export const FETCH_TEACHER_SUBJECTS_FAIL = "FETCH_TEACHER_SUBJECTS_FAIL";

export const FETCH_TEACHER_TESTS_START = "FETCH_TEACHER_TESTS_START";
export const FETCH_TEACHER_TESTS_SUCCESS = "FETCH_TEACHER_TESTS_SUCCESS";
export const FETCH_TEACHER_TESTS_FAIL = "FETCH_TEACHER_TESTS_FAIL";

export const FETCH_STUDENT_SUBJECTS_START = "FETCH_STUDENT_SUBJECTS_START";
export const FETCH_STUDENT_SUBJECTS_SUCCESS = "FETCH_STUDENT_SUBJECTS_SUCCESS";
export const FETCH_STUDENT_SUBJECTS_FAIL = "FETCH_STUDENT_SUBJECTS_FAIL";

export const FETCH_STUDENT_TESTS_START = "FETCH_STUDENT_TESTS_START";
export const FETCH_STUDENT_TESTS_SUCCESS = "FETCH_STUDENT_TESTS_SUCCESS";
export const FETCH_STUDENT_TESTS_FAIL = "FETCH_STUDENT_TESTS_FAIL";

export const FETCH_STUDENT_SOLVED_TESTS_START =
  "FETCH_STUDENT_SOLVED_TESTS_START";
export const FETCH_STUDENT_SOLVED_TESTS_SUCCESS =
  "FETCH_STUDENT_SOLVED_TESTS_SUCCESS";
export const FETCH_STUDENT_SOLVED_TESTS_FAIL =
  "FETCH_STUDENT_SOLVED_TESTS_FAIL";

export const GET_STUDENTS_MARKS_START = "GET_STUDENTS_MARKS_START";
export const GET_STUDENTS_MARKS_SUCCESS = "GET_STUDENTS_MARKS_SUCCESS";
export const GET_STUDENTS_MARKS_FAIL = "GET_STUDENTS_MARKS_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
