export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_SANDWICH_START = "PURCHASE_SANDWICH_START";
export const PURCHASE_SANDWICH_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_SANDWICH_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const FETCH_TEACHER_SUBJECTS_START = "FETCH_TEACHER_SUBJECTS_START";
export const FETCH_TEACHER_SUBJECTS_SUCCESS = "FETCH_TEACHER_SUBJECTS_SUCCESS";
export const FETCH_TEACHER_SUBJECTS_FAIL = "FETCH_TEACHER_SUBJECTS_FAIL";

export const FETCH_TEACHER_TESTS_START = "FETCH_TEACHER_TESTS_START";
export const FETCH_TEACHER_TESTS_SUCCESS = "FETCH_TEACHER_TESTS_SUCCESS";
export const FETCH_TEACHER_TESTS_FAIL = "FETCH_TEACHER_TESTS_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
